import React, { useEffect } from "react";
import { observer } from "mobx-react-lite";
import { Card, Box, Button, Grid } from "@material-ui/core";
import detection1 from './screencap/detection1.png'
import detection2 from './screencap/detection2.png'
import detection3 from './screencap/detection3.png'
import detection4 from './screencap/detection4.png'

declare let cv: any;
export const Info = observer(() => {


  return <>
    <Box p={5} >
      <Grid container spacing={1}>
        <Grid item xs={12} sm={12}>
          <h1>Welcome to the Deepfake Portal</h1>
          <br></br>
        </Grid>
        <Grid item xs={12} sm={12}>
          <h3>What is Deepfake Portal?</h3>
          <p>Deepfake portal allow users to generate and detect deepfakes with several algorithms, and review resources related to deepfakes, as a public education tool. For generation, users can upload their source video or live recording one with our recording service through webcam.
            Together with a source image uploaded, users can generate their deepfakes using either First Order Motion Model or X2Face Model. For detection, users can upload a video onto the portal to distinguish whether the content is generated by deepfakes.
          Four detection methods are used to identify deepfakes, with each test result showing to the users.At the Resources tab, you can read more about the deepfakes news, incidents and links to external articles</p>
        </Grid>
        <Grid item xs={12} sm={6}>
          <h3>Instructions on Generation</h3>
          <p>Step 1: Go to the "Generation" tab, you should see this page:</p>
          {/* <img  alt="No image" width ="600" src= {detection1}/> */}
          <p>Step 2: Choose upload video or live recording using webcam</p>
          <p>Step 2a: Upload a video by pressing the upload button. Crop your video to 256x256 for better quality.</p>
          {/* <img  alt="No image" src= /> */}
          <p>Step 2b: Start live recording by pressing start and stop when finish</p>
          {/* <img  alt="No image" src= /> */}
          <p>Step 3: Upload source image. Crop your image to 256x256 for better quality.</p>
          {/* <img  alt="No image" src= /> */}
          <p>Step 4: To generate deepfakes, press the buttons for corresponding methods:</p>
          {/* <img  alt="No image" src= /> */}
          <p>Step 5: Wait until you see the download button available:</p>
          {/* <img  alt="No image" src= /> */}
          <p>Step 6: Click into the button, you can see the vidoe preview and download:</p>
          {/* <img  alt="No image" src= /> */}
        </Grid>
        <Grid item xs={12} sm={6}>
          <h3>Instructions on Detection</h3>
          <p>Step 1: Go to the "Detection" tab, you should see this page:</p>
          <img  alt="No image" width ="600" src= {detection1}/>
          <p>Step 2: Upload a video by pressing the upload button. Crop your video to 300x300 for better quality. If the video is successfully uploaded, you should see this:</p>
          <img  alt="No image" width ="600" src= {detection2}/>
          <p>Step 3: Press "detect" to generate the Detection Report</p>
          <img  alt="No image" width ="600" src= {detection3}/>
          <p>Step 4: Wait until all the tests are finished. The results are displayed.</p>
          <img  alt="No image" width ="600" src= {detection4}/>
        </Grid>
      </Grid>
    </Box>
  </>;
});
